name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Pass projectId'
        required: false
        default: ''
        type: string
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  main:
    permissions:
      contents: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install handbrake-cli for video conversion
      run: sudo apt-get install handbrake-cli
    - name: Install playwright browsers
      run: pnpm exec playwright install --with-deps
    - name: Run playwright tests
      run: pnpm exec playwright test
      continue-on-error: true
    - name: Run videos upload script
      run: npx tsx core/upload.ts "${{ vars.PROJECT_ID }}"
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'ci: auto-commit results.json'
        add: 'results.json'
        push: true
    - name: Sync board
      run: npx tsx core/sync-board.ts "${{ vars.PROJECT_ID }}"
